from pyrogram import filters
from pyrogram.types import Message
from AloneMusic import app
import random

# ===== RÜYA SÖZLÜĞÜ (GENİŞ) =====
ruya_sozluk = {
    "su": "Huzur, arınma ve bereket anlamına gelir.",
    "deniz": "Hayatında büyük değişimlerin yaklaşabileceğini gösterir.",
    "yılan": "Kıskanç veya gizli bir düşmana işaret edebilir.",
    "para": "Maddi fırsatlar veya yeni kazanç kapıları.",
    "uçmak": "Özgürlük ve hedeflerine ulaşma arzusu.",
    "düşmek": "Kontrol kaybı veya endişe yaşadığını gösterebilir.",
    "ev": "Aile ve iç huzurla ilgili gelişmeler.",
    "bebek": "Yeni başlangıçlar ve umut.",
    "ateş": "Güçlü duygular ve önemli değişim.",
    "ölmek": "Bir dönemin kapanıp yeni bir dönemin başlaması.",
    "köpek": "Sadık bir dost veya destek.",
    "kedi": "Sezgiler ve gizemli durumlar.",
    "kuş": "Özgürlük ve güzel haber.",
    "araba": "Hayatının yönünü değiştirecek bir karar.",
    "yol": "Yeni bir yolculuk veya hayat değişimi.",
    "altın": "Büyük şans ve değerli fırsatlar.",
    "yağmur": "Arınma ve duygusal rahatlama.",
    "kar": "Sessizlik, sakinlik veya bekleme dönemi.",
    "ağaç": "Gelişim ve köklenme.",
    "dağ": "Zor ama değerli bir hedef.",
  "bulut": "Kafanı karıştıran düşünceler veya geçici belirsizlikler.",
  "gökkuşağı": "Zorluklardan sonra gelecek mutluluk ve umut.",
  "deniz feneri": "Sana yol gösterecek bir insan veya önemli bir işaret.",
  "ada": "Yalnız kalma isteği veya kendini keşfetme dönemi.",
  "kum": "Geçici durumlar veya hızla değişen şartlar.",
  "çöl": "Sabır gerektiren zor bir dönem.",
  "orman": "Keşfedilecek yeni fırsatlar ve bilinmeyen yollar.",
  "mağara": "İç dünyana dönme ve gizli düşüncelerle yüzleşme.",
  "kılıç": "Kararlı bir karar veya mücadele.",
  "kalkan": "Kendini koruma ihtiyacı veya savunma.",
  "zincir": "Kendini kısıtlanmış hissettiğin bir durum.",
  "taç": "Başarı, saygı ve yükselme.",
  "taht": "Güç ve sorumluluk sahibi olma.",
  "bayrak": "Başarı, gurur ve hedeflere ulaşma.",
  "hediye": "Beklenmedik güzel bir gelişme.",
  "mektup": "Yakında alacağın bir haber veya mesaj.",
  "telefon": "İletişim kurman gereken önemli bir kişi.",
  "pencere": "Yeni bakış açıları ve fırsatlar.",
  "çit": "Sınırlar koyma veya bir engelle karşılaşma.",
  "bahçe": "Emek verdiğin bir şeyin büyümesi ve gelişmesi.",
  "tohum": "Gelecekte büyüyecek yeni fikirler veya projeler.",
  "fırtına": "Duygusal karmaşa veya ani olaylar.",
  "yıldırım": "Ani farkındalık veya beklenmedik gelişme.",
  "gemi": "Uzak yolculuk veya hayatında büyük bir değişim.",
  "liman": "Güvenli bir yere ulaşma ve huzur bulma.",
  "tren": "Planlı ilerleyen bir süreç veya kaderin yönlendirmesi.",
  "bilet": "Yeni bir fırsat veya başlangıç.",
  "harita": "Hayatında yön bulma veya plan yapma.",
  "pusula": "Doğru yolu bulma ve karar verme.",
  "köy": "Sadelik, huzur ve geçmişe özlem.",
  "şehir": "Sosyal hayatın hareketlenmesi ve yeni insanlarla tanışma.",
  "sokak": "Hayatında ilerlediğin yol ve karşılaşacağın fırsatlar.",
  "köprüden geçmek": "Eski bir dönemi geride bırakıp yeni bir sürece girme.",
  "kilit": "Henüz çözülmemiş bir mesele veya gizli bir durum.",
  "bıçak": "Keskin bir karar verme veya bir ilişkiyi sonlandırma.",
  "masa": "Toplantı, konuşma veya önemli bir karar süreci.",
  "sandalye": "Dinlenme ihtiyacı veya kısa bir duraklama.",
  "kapalı kapı": "Şu an erişemediğin bir fırsat.",
  "açık kapı": "Yeni fırsatlar ve başlangıçlar.",
  "ışık": "Gerçeğin ortaya çıkması ve farkındalık.",
  "karanlık": "Belirsizlik veya bilinmeyen durumlar.",
  "el": "Yardım, destek veya bir anlaşma.",
  "yüz": "Bir kişiyle ilgili gerçek duyguların ortaya çıkması.",
  "göz": "Dikkatli olman gereken bir durum veya sezgi.",
  "gülmek": "Mutluluk ve iç huzur.",
  "ağlamak": "Duygusal boşalma ve rahatlama.",
  "koşmak": "Hedeflerine hızlı bir şekilde yaklaşma.",
  "saklanmak": "Bir durumdan kaçınma isteği.",
  "yakalanmak": "Bir gerçeğin ortaya çıkması.",
  "kaybolmak": "Hayatta yönünü aradığın bir dönem.",
  "bulmak": "Uzun zamandır aradığın bir çözümü keşfetmek.",
  "yüzmek": "Duygularınla başa çıkma ve ilerleme.",
  "boğulmak": "Yoğun stres veya baskı altında hissetmek.",
  "kurtulmak": "Zor bir durumdan çıkış yolu bulmak.",
  "yemek": "Ruhsal veya fiziksel ihtiyaçların karşılanması.",
  "su içmek": "Rahatlama ve enerji toplama.",
  "sofra": "Aile, birlik ve paylaşım.",
  "misafir": "Hayatına girecek yeni bir kişi.",
  "düğün": "Büyük bir değişim veya yeni başlangıç.",
  "mezar": "Geçmişte kalan bir konuyla yüzleşme.",
#isim
  "ahmet": "Güvenilir, dürüst ve çevresi tarafından sevilen bir kişiyi temsil eder.",
  "mehmet": "Güçlü karakter, sabır ve saygınlık anlamına gelir.",
  "ali": "Cesaret, liderlik ve güçlü bir iradeyi simgeler.",
  "mustafa": "Seçilmişlik, saygınlık ve güçlü bir kişiliği temsil eder.",
  "emre": "Dostluk, samimiyet ve içtenliği ifade eder.",
  "can": "Hayat enerjisi, sevgi ve yakın bağları simgeler.",
  "burak": "Hız, ilerleme ve başarıya ulaşma isteğini temsil eder.",
  "mert": "Dürüstlük, cesaret ve güvenilirlik anlamına gelir.",
  "kerem": "Cömertlik, yardımseverlik ve iyi kalpliliği simgeler.",
  "serkan": "Güçlü irade ve liderlik özelliklerini temsil eder.",
  "tolga": "Güç, koruyuculuk ve dayanıklılık anlamına gelir.",
  "kaan": "Otorite, güç ve yönetme yeteneğini simgeler.",
  "yusuf": "Sabır, güzellik ve iyi niyeti temsil eder.",
  "ibrahim": "Bilgelik, güven ve sağlam karakteri ifade eder.",
  "ömer": "Adalet, doğruluk ve güçlü ahlaki değerler.",
  "hasan": "İyilik, merhamet ve güzel ahlakı simgeler.",
  "hüseyin": "Sadakat, fedakarlık ve güçlü bağlar.",
  "selim": "Sakinlik, huzur ve dengeli bir karakter.",
  "barış": "Uzlaşma, huzur ve dostluk anlamına gelir.",
  "deniz": "Özgür ruh, geniş düşünce ve değişim.",
  "ayşe": "Şefkat, zarafet ve güçlü aile bağları.",
  "fatma": "Sabır, merhamet ve güçlü bir anne figürü.",
  "zeynep": "Güzellik, zarafet ve sevilen bir kişilik.",
  "elif": "Saflık, sadelik ve güçlü bir karakter.",
  "eda": "Nazik davranışlar ve zarif bir kişiliği simgeler.",
  "buse": "Mutluluk, neşe ve pozitif enerji.",
  "selin": "Sakinlik, huzur ve berrak düşünceler.",
  "melis": "Tatlılık, sevgi ve sıcak bir karakter.",
  "seda": "Güzel haberler ve dikkat çeken bir ses.",
  "gamze": "Sevimlilik, çekicilik ve sıcak bir gülümseme.",
  "naz": "Zarafet, incelik ve hassas duygular.",
  "ece": "Kraliçe gibi güçlü ve saygın bir karakter.",
  "esra": "Hızlı düşünme ve güçlü sezgiler.",
  "dilara": "Kalpleri mutlu eden, sevgi dolu kişi.",
  "tuğçe": "Zariflik ve içtenlik.",
  "gizem": "Sır dolu ve merak uyandıran bir kişilik.",
  "şeyma": "Güzellik ve dikkat çeken bir karakter.",
  "aslı": "Gerçeklik, sadelik ve samimiyet.",
  "cansu": "Hayat enerjisi ve canlılık.",
  "derya": "Derin duygular ve geniş bir bakış açısı.",
  "ipek": "Naziklik, yumuşaklık ve zarafet.",
  "gül": "Sevgi, güzellik ve mutluluk.",
  "çiğdem": "Yenilik, bahar ve umut.",
  "sevgi": "Şefkat, bağlılık ve güçlü duygular.",
  "umut": "İyi bir geleceğe olan inanç.",
  "onur": "Saygınlık, gurur ve güçlü karakter.",
  "özgür": "Bağımsızlık ve kendi yolunu çizme isteği.",
  "erdem": "Ahlak, doğruluk ve iyi davranışlar.",
  "acelya": "Zarafet, doğallık ve dikkat çeken güzellik.",
  "🗣️": "bir bakalım ne varmış",
  "adile": "Adaletli, merhametli ve güvenilir bir kişilik.",
  "afife": "Temizlik, saflık ve güçlü karakter.",
  "aida": "Mutluluk ve neşe getiren kişi.",
  "ajda": "Güçlü ve dikkat çekici bir karakter.",
  "alara": "Parlaklık, enerji ve canlılık.",
  "aleyna": "Değerli ve özel bir kişi.",
  "alya": "Yüksek hedefler ve zarif bir karakter.",
  "amber": "Gizem ve sıcak bir kişilik.",
  "arzu": "İstekler, hayaller ve güçlü duygular.",
  "asel": "Şifa, saflık ve iyi kalplilik.",
  "asena": "Güç, liderlik ve cesaret.",
  "asya": "Gizemli, derin düşünceli bir karakter.",
  "ateş": "Tutku, enerji ve güçlü duygular.",
  "ayben": "Ay gibi parlak ve dikkat çekici.",
  "aybuke": "Zarif ve saygın bir karakter.",
  "aydan": "Aydınlık, umut ve pozitif enerji.",
  "ayfer": "Güzellik ve iç huzur.",
  "ayla": "Parlaklık ve zarafet.",
  "aynur": "Ay ışığı gibi sakin ve huzurlu.",
  "aysel": "Işık, umut ve pozitiflik.",
  "aysima": "Ay gibi güzel ve dikkat çekici.",
  "ayten": "Zarif ve güçlü bir karakter.",
  "bahar": "Yenilik, umut ve tazelenme.",
  "banu": "Saygınlık ve güçlü kişilik.",
  "belgin": "Açık fikirli ve net düşünceler.",
  "benan": "Güzellik ve dikkat çeken bir karakter.",
  "beren": "Güçlü ve akıllı bir kişilik.",
  "beril": "Değerli ve nadir bir karakter.",
  "beste": "Uyum, sanat ve yaratıcılık.",
  "betül": "Saflık ve güçlü inanç.",
  "beyza": "Temizlik, saflık ve masumiyet.",
  "bilgehan": "Bilgelik ve liderlik.",
  "burcu": "Duygusal derinlik ve sezgi.",
  "canan": "Sevilen, değer verilen kişi.",
  "ceyda": "Neşeli ve enerjik karakter.",
  "cevriye": "Güçlü ve dayanıklı bir kişilik.",
  "damla": "Saflık, doğallık ve tazelik.",
  "defne": "Zarafet, başarı ve güzellik.",
  "demet": "Birlik, uyum ve bağlılık.",
  "denisa": "Özgürlük ve geniş düşünce.",
  "dicle": "Güçlü akış ve değişim.",
  "dilan": "Sevgi ve sıcak duygular.",
  "duru": "Saflık, sadelik ve berraklık.",
  "eda nur": "Zarafet ve ruhsal huzur.",
  "ece nur": "Saygınlık ve iç huzur.",
  "eda su": "Nazik ve huzur veren bir karakter.",
  "ela": "Güzellik, dikkat çekicilik ve zarafet."
}

# ===== FAL CEVAPLARI (GENİŞ) =====
fal_listesi = [
"Bugün şans seninle.",
"Yakında güzel bir haber alacaksın.",
"Beklediğin bir mesaj gelebilir.",
"Yeni bir fırsat kapını çalabilir.",
"Kalbini dinlersen doğru yolu bulacaksın.",
"Sabırlı olman gereken bir dönem.",
"Beklenmedik bir tanışma olabilir.",
"Hayatında küçük ama önemli bir değişim var.",
"Eski bir dost tekrar hayatına girebilir.",
"Yakında güzel bir yolculuk görünüyor.",
"Şansın özellikle akşam saatlerinde artacak.",
"Planlarını biraz ertelemen gerekebilir.",
"Sürpriz bir teklif alabilirsin.",
"Yeni bir başlangıç seni bekliyor.",
"Uzun zamandır düşündüğün bir konu netleşecek.",
"Hayatında yeni bir kapı açılabilir.",
"Uzun zamandır beklediğin gelişme yakında.",
"Birinden güzel bir destek göreceksin.",
"İç sesin sana doğru yolu gösterecek.",
"Bugün aldığın karar önemli olabilir.",
"Şanslı bir karşılaşma yaşayabilirsin.",
"Hayatında yeni bir sayfa açılıyor.",
"Beklenmedik bir fırsat yakalayabilirsin.",
"Yakında sevindirici bir gelişme var.",
"Uzun süredir düşündüğün plan gerçekleşebilir.",
"Bir dileğin gerçekleşmeye çok yakın.",
"Bugün pozitif enerji seninle.",
"Bir arkadaşın sana önemli bir fikir verebilir.",
"Hayatında güzel bir değişim başlayabilir.",
"Yeni bir ortam seni bekliyor.",
"Şanslı bir gün seni bekliyor.",
"Bugün alacağın haber seni mutlu edebilir.",
"Yakında seni şaşırtacak bir gelişme olacak.",
"Beklenmedik bir fırsat ortaya çıkabilir.",
"Hayatında huzurlu bir dönem başlayabilir.",
"Yeni bir tanışma hayatına renk katabilir.",
"Bir dileğin yakında gerçekleşebilir.",
"Yakında güzel bir sürpriz yaşayabilirsin.",
"Hayatında olumlu gelişmeler olacak.",
"Sabırlı olursan istediğin şeye ulaşabilirsin.",
"Bugün kendine güvenmen gereken bir gün.",
"Yakında önemli bir karar verebilirsin.",
"Beklediğin cevap yakında gelebilir.",
"Şansın yavaş yavaş artıyor.",
"Yeni bir başlangıç için doğru zamandasın.",
"Hayatında yeni bir fırsat doğabilir.",
"Yakında seni mutlu edecek bir gelişme var.",
"Bir arkadaşından güzel bir haber alabilirsin.",
"Beklenmedik bir yolculuk olabilir.",
"Hayatında güzel bir değişim yaklaşıyor.",
"Bugün güzel bir gelişme yaşayabilirsin.",
"Uzun zamandır istediğin şey yakında olabilir.",
"Yeni bir fikir sana başarı getirebilir.",
"Şanslı bir dönem başlıyor.",
"Yakında hayatına yeni insanlar girebilir.",
"Bir konuda iç sesini dinlemelisin.",
"Beklediğin fırsat yakında ortaya çıkabilir.",
"Bugün sana ilham verecek bir şey yaşayabilirsin.",
"Bir hedefin yakında gerçekleşebilir.",
"Hayatında güzel bir sürpriz olabilir.",
"Beklenmedik bir gelişme seni mutlu edebilir.",
"Yeni bir kapı açılabilir.",
"Hayatında olumlu bir dönüş olabilir.",
"Yakında seni sevindirecek bir haber var.",
"Bir fırsatı iyi değerlendirmen gerekebilir.",
"Bugün şanslı bir karşılaşma yaşayabilirsin.",
"Hayatında yeni bir başlangıç olabilir.",
"Bir dileğin gerçekleşmeye yakın.",
"Yakında önemli bir konuşma yapabilirsin.",
"Beklenmedik bir destek alabilirsin.",
"Yeni bir plan sana başarı getirebilir.",
"Hayatında pozitif bir değişim olabilir.",
"Yakında sevindirici bir mesaj alabilirsin.",
"Bugün iç huzuru hissedebilirsin.",
"Şansın giderek artıyor.",
"Bir karar hayatını değiştirebilir.",
"Yakında güzel bir fırsat seni bulacak.",
"Hayatında yeni bir yol açılabilir.",
"Beklenmedik bir mutluluk yaşayabilirsin.",
"Bir arkadaşın sana destek olabilir.",
"Bugün enerjin oldukça yüksek.",
"Hayatında umut verici bir gelişme olabilir.",
"Yeni bir fikir başarı getirebilir.",
"Yakında seni mutlu edecek bir teklif olabilir.",
"Hayatında güzel bir sürpriz olabilir.",
"Bugün alacağın bir haber seni sevindirebilir.",
"Yeni bir başlangıç yapabilirsin.",
"Şanslı bir dönem başlıyor.",
"Hayatında huzur artabilir.",
"Yakında bir dileğin gerçekleşebilir.",
"Beklenmedik bir fırsat seni bulabilir.",
"Bugün önemli bir gelişme yaşayabilirsin.",
"Yeni bir kapı açılabilir.",
"Hayatında güzel bir haber olabilir.",
"Bir arkadaşın sana iyi bir fikir verebilir.",
"Yakında sevindirici bir gelişme olacak.",
"Hayatında yeni bir başlangıç olabilir.",
"Bir hedefin yakında gerçekleşebilir.",
"Beklediğin mesaj yakında gelebilir.",
"Yeni bir fırsat ortaya çıkabilir.",
"Şansın artıyor.",
"Yakında seni mutlu edecek bir haber var.",
"Hayatında olumlu gelişmeler olacak.",
"Bir karar yeni kapılar açabilir.",
"Yakında güzel bir sürpriz yaşayabilirsin.",
"Bugün şans senin yanında olabilir.",
"Yeni bir başlangıç seni bekliyor.",
"Hayatında umut dolu bir dönem olabilir.",
"Beklenmedik bir teklif alabilirsin.",
"Yakında güzel bir tanışma olabilir.",
"Şanslı bir gün yaşayabilirsin.",
"Hayatında güzel bir gelişme olabilir.",
"Bir dileğin yakında gerçekleşebilir.",
"Yeni bir fırsat kapını çalabilir.",
"Bugün güzel bir haber alabilirsin.",
"Hayatında yeni bir yol açılabilir.",
"Beklenmedik bir mutluluk yaşayabilirsin.",
"Yakında sevindirici bir gelişme olabilir.",
"Şansın artmaya devam ediyor.",
"Hayatında güzel bir değişim olabilir.",
"Bir fırsat seni bekliyor.",
"Yeni bir kapı açılabilir.",
"Bugün şanslı bir gün olabilir.",
"Yakında güzel bir sürpriz olabilir.",
"Hayatında yeni bir başlangıç olabilir.",
"Bir hedefin yakında gerçekleşebilir.",
"Beklenmedik bir fırsat seni bulabilir.",
"Yeni bir plan sana başarı getirebilir.",
"Yakında seni mutlu edecek bir gelişme var.",
"Hayatında güzel bir değişim olabilir.",
"Bir dileğin gerçekleşebilir.",
"Bugün pozitif bir gelişme yaşayabilirsin.",
"Yakında sevindirici bir haber alabilirsin.",
"Hayatında yeni bir fırsat olabilir.",
"Şanslı bir dönem başlıyor.",
"Beklenmedik bir destek alabilirsin.",
"Yeni bir başlangıç seni bekliyor.",
"Yakında güzel bir sürpriz olabilir.",
"Hayatında umut dolu bir gelişme olabilir.",
"Bir karar hayatında değişim getirebilir.",
"Yakında seni mutlu edecek bir haber var.",
"Bugün güzel bir fırsat yakalayabilirsin.",
"Hayatında yeni bir yol açılabilir.",
"Şansın giderek artıyor.",
"Yakında güzel bir gelişme olabilir.",
"Beklenmedik bir mutluluk yaşayabilirsin.",
"Hayatında yeni bir başlangıç olabilir.",
"Bir dileğin yakında gerçekleşebilir.",
"Yeni bir fırsat seni bekliyor.",
"Yakında sevindirici bir haber alabilirsin.",
"Hayatında güzel bir sürpriz olabilir.",
"Bugün şanslı bir gelişme yaşayabilirsin.",
"Yeni bir kapı açılabilir.",
"Hayatında olumlu bir değişim olabilir.",
"Yakında seni mutlu edecek bir gelişme olabilir.",
"Şanslı bir dönem seni bekliyor."
]
# ===== BURÇ YORUMLARI =====
burclar = {
    "koç": "Enerjin yüksek. Yeni başlangıçlar için uygun bir gün.",
    "boğa": "Maddi konularda dikkatli olman gerekebilir.",
    "ikizler": "İletişim ve sosyal çevre ön planda.",
    "yengeç": "Aile ve duygusal konular gündemde.",
    "aslan": "Liderlik özelliklerin dikkat çekecek.",
    "başak": "Detaylara odaklanarak başarı yakalayabilirsin.",
    "terazi": "İlişkilerde denge kurman önemli.",
    "akrep": "Sezgilerin seni doğru yönlendirebilir.",
    "yay": "Yeni fikirler ve planlar ortaya çıkabilir.",
    "oğlak": "Çalışkanlığın sana başarı getirecek.",
    "kova": "Yaratıcı düşüncelerin ön plana çıkacak.",
    "balık": "Duyguların ve hayal gücün güçlü."
}

# ===== TAROT =====
tarot_kartlari = [
    "🃏 Deli – Yeni başlangıçlar, macera ve bilinmeyene adım atmak.",
    "🃏 Büyücü – Güç, yetenek ve potansiyelini kullanma.",
    "🃏 Başrahibe – Sezgiler, gizli bilgiler ve iç sesini dinleme.",
    "🃏 İmparatoriçe – Bereket, yaratıcılık ve şefkat.",
    "🃏 İmparator – Otorite, düzen ve liderlik.",
    "🃏 Aziz (Başrahip) – Gelenekler, bilgi ve ruhsal rehberlik.",
    "🃏 Âşıklar – Aşk, uyum ve önemli seçimler.",
    "🃏 Savaş Arabası – Kararlılık, ilerleme ve zafer.",
    "🃏 Güç – İçsel güç, sabır ve cesaret.",
    "🃏 Ermiş – İçsel arayış, yalnızlık ve bilgelik.",
    "🃏 Kader Çarkı – Şans, kader ve beklenmedik değişimler.",
    "🃏 Adalet – Denge, doğruluk ve adil kararlar.",
    "🃏 Asılan Adam – Bekleme, fedakârlık ve farklı bakış açısı.",
    "🃏 Ölüm – Büyük dönüşüm ve yeni başlangıç.",
    "🃏 Denge – Sabır, uyum ve orta yolu bulma.",
    "🃏 Şeytan – Bağımlılıklar, tutkular ve gizli arzular.",
    "🃏 Kule – Ani değişim, sarsıcı olaylar ve eski düzenin yıkılması.",
    "🃏 Yıldız – Umut, ilham ve ruhsal huzur.",
    "🃏 Ay – Gizem, sezgi ve belirsizlik.",
    "🃏 Güneş – Mutluluk, başarı ve pozitif enerji.",
    "🃏 Mahkeme (Yargı) – Uyanış, hesaplaşma ve önemli kararlar.",
    "🃏 Dünya – Tamamlanma, başarı ve yeni bir döngü."
]

# ===== RÜYA =====
@app.on_message(filters.command("ruya"))
async def ruya(client, message: Message):

    if len(message.command) < 2:
        await message.reply("Rüyanı yaz.\nÖrnek:\n`/ruya rüyamda yılan gördüm`")
        return

    text = " ".join(message.command[1:]).lower()
    bulunan = []

    for kelime, yorum in ruya_sozluk.items():
        if kelime in text:
            bulunan.append(f"🔎 **{kelime}** → {yorum}")

    if bulunan:
        await message.reply("🌙 **Rüya Analizi**\n\n" + "\n".join(bulunan))
    else:
        await message.reply("🔮 Rüyada belirgin sembol algılanamadı.")

# ===== FAL =====
@app.on_message(filters.command("fal"))
async def fal(client, message: Message):

    cevap = random.choice(fal_listesi)

    await message.reply(f"🔮 **Fal Yorumu**\n\n{cevap}")

# ===== BURÇ =====
@app.on_message(filters.command("burc"))
async def burc(client, message: Message):

    if len(message.command) < 2:
        await message.reply("Burcunu yaz.\nÖrnek:\n`/burc aslan`")
        return

    burc = message.command[1].lower()

    if burc in burclar:
        await message.reply(f"♈ **{burc.capitalize()} Burcu**\n\n{burclar[burc]}")
    else:
        await message.reply("Geçerli bir burç yaz.")

# ===== AŞK UYUMU =====
@app.on_message(filters.command("askuyumu"))
async def ask(client, message: Message):

    if len(message.command) < 3:
        await message.reply("Örnek:\n`/askuyumu koç akrep`")
        return

    oran = random.randint(40, 100)

    await message.reply(f"❤️ **Burç Uyumu**\n\nUyum oranı: **%{oran}**")

# ===== TAROT =====
@app.on_message(filters.command("tarot"))
async def tarot(client, message: Message):

    kart = random.choice(tarot_kartlari)

    await message.reply(f"🃏 **Tarot Kartın**\n\n{kart}")
